apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: sample-app
  owner: demo-user
commonAnnotations:
  oncallPager: 800-555-1212
namespace: nginx-ns
namePrefix: mgm-
resources:
  - deploy.yaml
  - service.yaml
